version: '3.8'

networks:
  flinkflow-net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - flinkflow-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    networks:
      - flinkflow-net

  apicurio:
    image: apicurio/apicurio-registry-mem:latest-release
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
      - LOG_LEVEL=DEBUG
    networks:
      - flinkflow-net

  jobmanager:
    image: flink:1.18-java17
    depends_on:
      - kafka
    environment:
      - |      
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        sql-gateway.endpoint.rest.address: 0.0.0.0
    command: jobmanager
    ports:
      - "8081:8081" # Flink Dashboard
    networks:
      - flinkflow-net

  taskmanager:
    image: flink:1.18-java17
    depends_on:
      - jobmanager
    environment:
      - |      
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    command: taskmanager
    networks:
      - flinkflow-net

  sql-gateway:
    image: flink:1.18-java17
    depends_on:
      - jobmanager
    environment:
      - |      
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        sql-gateway.endpoint.rest.address: 0.0.0.0
        sql-gateway.endpoint.rest.port: 8083
    command: bin/sql-gateway.sh start-foreground
    ports:
      - "8083:8083" # Flink SQL Gateway
    networks:
      - flinkflow-net


