apiVersion: flinkflow.io/v1alpha1
kind: Pipeline
metadata:
  name: sql-window-aggregation
spec:
  name: "Flink SQL Tumbling Window Example"
  parallelism: 1
  steps:
    - type: source
      name: click_events
      connector: static-source
      properties:
        content: '{"userId": "u1", "eventTime": "2026-06-21T10:00:01", "click": 1}|{"userId": "u2", "eventTime": "2026-06-21T10:00:03", "click": 1}|{"userId": "u1", "eventTime": "2026-06-21T10:00:07", "click": 1}|{"userId": "u2", "eventTime": "2026-06-21T10:00:12", "click": 1}'

    - type: sql
      name: window-clicks
      properties:
        schema.userId: "string"
        schema.click: "int"
        schema.eventTime: "timestamp"
        watermark.column: "eventTime"
        watermark.delay: "2"
        tableName: "clicks"
        query: |
          SELECT 
            userId,
            TUMBLE_START(eventTime, INTERVAL '10' SECOND) AS window_start,
            TUMBLE_END(eventTime, INTERVAL '10' SECOND) AS window_end,
            SUM(click) AS total_clicks
          FROM clicks
          GROUP BY userId, TUMBLE(eventTime, INTERVAL '10' SECOND)

    - type: sink
      name: console-sink
